name: brain-game

on: push

jobs:
  build:

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      uses: actions/checkout@v2
      name: run linter
      # Run Linter
      run: |
        make lint